In [16]:
import numpy as np
import tqdm

In [17]:
def hardlims(input):
  return (input >0 ).astype(float)

In [18]:
def delta_rule(X,Y, weights,n_epochs):
  dims = X.shape[-1]
  for _ in tqdm.tqdm(range(n_epochs)):
    for x,y in zip(X,Y):
      sum = x@weights
      e = y - hardlims(sum)
      # print(e*x)
      weights = weights + e*x
      # print("w", weights, "k")
  return weights

#AND

In [19]:
#AND
X = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y = np.array([0,0,0,1])

In [20]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.52825269 0.99819366 0.26373186]
[0.52825269 0.79198454 1.52644635 1.7901782 ]
[1. 1. 1. 1.]



In [21]:
weights = delta_rule(X,Y, weights,n_epochs=100000)

100%|██████████| 100000/100000 [00:04<00:00, 24056.67it/s]


In [22]:
print("Wagi")
print(X@weights)
print(hardlims(X@weights))
Y

Wagi
[-2.47174731 -1.20801546 -0.47355365  0.7901782 ]
[0. 0. 0. 1.]


array([0, 0, 0, 1])

#OR

In [23]:
#OR
X = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y = np.array([0,1,1,1])

In [24]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.4662892  0.79627233 0.82702042]
[0.4662892  1.29330962 1.26256153 2.08958195]
[1. 1. 1. 1.]



In [25]:
weights = delta_rule(X,Y, weights,n_epochs=100000)

100%|██████████| 100000/100000 [00:04<00:00, 24210.93it/s]


In [26]:
print("Wagi")
print(X@weights)
print(hardlims(X@weights))
Y

Wagi
[-0.5337108   0.29330962  0.26256153  1.08958195]
[0. 1. 1. 1.]


array([0, 1, 1, 1])

#XOR

In [27]:
#XOR
X = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y = np.array([0,1,1,0])

In [28]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.68847103 0.93638854 0.78498845]
[0.68847103 1.47345948 1.62485956 2.40984802]
[1. 1. 1. 1.]



In [29]:
weights = delta_rule(X,Y, weights,n_epochs=100000)

100%|██████████| 100000/100000 [00:04<00:00, 24861.95it/s]


In [30]:
print("Wagi")
print(X@weights)
print(hardlims(X@weights))
Y

Wagi
[ 0.68847103  0.47345948 -0.37514044 -0.59015198]
[1. 1. 0. 0.]


array([0, 1, 1, 0])