In [13]:
import numpy as np
import tqdm

In [14]:
def hardlims(input):
  return (input >0 ).astype(float)

In [15]:
def delta_rule(X,Y, weights,n_epochs):
  dims = X.shape[-1]
  for _ in tqdm.tqdm(range(n_epochs)):
    for x,y in zip(X,Y):
      sum = x@weights
      e = y - hardlims(sum)
      # print(e*x)
      weights = weights + e*x
      # print("w", weights, "k")
  return weights


#Dane separowalne

In [16]:
#AND
n_inputs = 100
n_dims = 2
X = np.random.random((n_inputs, n_dims + 1))
Y = np.random.randint(0,2,size=(n_inputs))
#na 1 wspolrzednej wartosci dodatnie lub ujemne dadza separowalnosc
X[Y== 0] = X[Y== 0] + 100
X[Y== 1] = X[Y== 1] - 100

In [17]:
X[:5]

array([[100.11856702, 100.35244996, 100.43561758],
       [100.36614636, 100.26213851, 100.9385749 ],
       [100.0659043 , 100.61909618, 100.11794145],
       [-99.70783609, -99.28024814, -99.41742399],
       [-99.58451948, -99.24401731, -99.92013485]])

In [18]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.55375585 0.0448724  0.69163114]
[ 129.40869811  129.88960508  129.17178618 -128.42892679 -128.70670423
 -128.25691309 -128.65572987 -128.49607314  129.67657952 -128.25245064
 -128.86930315  130.0796512  -128.36326221  129.47871489  129.75188985
  129.58366743  129.97678562  130.04887077  129.48893407 -128.61190492
 -127.78715228  129.61559647  129.41547226  130.24878338 -128.46105088
  129.39863676 -128.10261749 -128.32621955 -128.29701783  129.37158238
 -128.5169262  -128.78494741 -128.81836956  129.72485106  129.38520958
 -128.31239259  129.50167958  129.55508263  129.75086057 -128.6342024
 -128.40173146 -128.52356514 -128.67734407  129.81547779 -128.1977463
 -128.35120115 -128.39959382 -128.71273496 -128.99000143 -128.36328419
  130.1234795   129.96337879  130.06319516 -128.36443973  129.42425968
  129.82494567  129.08034903 -128.69818198  129.81474434 -128.44357468
 -128.48775733 -128.60014914  129.18232735 -128.69599724  129.23446423
 -128.50758452  130.04325909 -128.2704593  -

In [19]:
weights = delta_rule(X,Y, weights,n_epochs=10000)

100%|██████████| 10000/10000 [00:08<00:00, 1172.58it/s]


In [20]:
print("Wagi")
print(X@weights)
predictions = hardlims(X@weights)
print(predictions)
print(Y)
print(np.average(np.abs(Y - predictions)))


Wagi
[-30052.24625501 -30118.00449157 -30042.06325495  29802.24325249
  29836.47341716  29759.11223968  29876.30080677  29845.93062169
 -30069.0936958   29816.60519188  29877.56848762 -30155.89485844
  29830.44155475 -30107.81028406 -30109.97557683 -30107.41707173
 -30183.56437742 -30141.77681419 -30060.64303741  29842.38308238
  29685.58021626 -30108.04885497 -30047.88368094 -30222.11320147
  29834.69217859 -30077.57832317  29730.9874166   29835.92203005
  29827.15769665 -30079.57288329  29840.13849249  29834.05119602
  29842.15406228 -30067.15385563 -30056.76565978  29813.80227768
 -30133.15992276 -30110.02043927 -30126.46816996  29839.70252776
  29812.34226593  29845.51999826  29855.50849252 -30174.76734803
  29782.34694267  29763.58539496  29829.57080366  29832.88363458
  29951.62230346  29782.10439901 -30181.83270186 -30151.76421145
 -30196.51327211  29840.1936328  -30040.20201776 -30128.33438204
 -30003.47888401  29905.3011241  -30108.45563218  29860.83635107
  29836.55325504  29

#Dane nieseparowalne

In [21]:
#AND
n_inputs = 100
n_dims = 2
X = np.random.random((n_inputs, n_dims + 1))
Y = np.random.randint(0,2,size=(n_inputs))

In [22]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.81816962 0.1320527  0.16457633]
[0.89863522 0.32648206 0.45910249 0.54158379 0.17299277 0.40256389
 0.84422725 0.49912019 0.32758843 0.22973459 0.48648523 0.54756958
 0.13206855 0.89572103 0.66291223 0.75372524 0.8946239  0.24997587
 0.64411485 0.20250094 1.01136708 0.49306172 0.62538732 0.23490114
 0.75614363 0.64059715 0.41602353 0.41907698 0.24190916 0.92480257
 0.28975817 0.13869401 0.54375343 0.68822409 0.57713613 0.29103062
 0.71976099 0.83200466 0.23677738 0.62321671 0.73734525 0.65770254
 0.70765611 0.65512967 0.48998416 0.5218642  0.19089961 0.43851601
 0.36253941 0.32813562 0.86199097 0.21222648 0.30971552 0.69142074
 0.84795642 0.34089004 0.96809674 0.88812753 0.30111166 0.34549302
 0.96375858 0.6720723  0.80394867 0.2659331  0.9054134  0.98300987
 0.88518751 0.56409744 0.71318658 0.24712433 0.10165218 0.32997897
 0.19800706 0.96654769 0.50952755 0.76667825 0.8701997  0.29540843
 0.63531233 0.78478581 0.76415682 0.5682501  0.8551771  0.47476863
 0.84659954 0.26864944 0.75

In [23]:
weights = delta_rule(X,Y, weights,n_epochs=10000)

100%|██████████| 10000/10000 [00:08<00:00, 1184.19it/s]


In [24]:
print("Wagi")
print(X@weights)
predictions = hardlims(X@weights)
print(predictions)
print(Y)
print(np.average(np.abs(Y - predictions)))

Wagi
[0.50105721 0.351412   0.43268975 0.36375524 0.28887123 0.25032964
 0.45426915 0.24278949 0.12813542 0.29795018 0.32761223 0.5574745
 0.26152251 0.5032956  0.57928713 0.46058443 0.70765604 0.35422446
 0.27435577 0.25936727 0.67907095 0.27796068 0.52793998 0.34955924
 0.65175453 0.35295973 0.4672097  0.39464313 0.36524    0.72934743
 0.39580813 0.24448824 0.23958507 0.4848712  0.36824717 0.29335125
 0.35127853 0.48039083 0.330047   0.43046863 0.56396144 0.48081659
 0.53401057 0.41504132 0.4455468  0.5711442  0.18180786 0.58328081
 0.25241659 0.41193863 0.70944067 0.30591124 0.26845236 0.43261439
 0.6667485  0.38529832 0.56751296 0.58742845 0.28399704 0.40765541
 0.66162633 0.53726146 0.47588048 0.20625147 0.5959547  0.62323505
 0.58987821 0.3917586  0.63683186 0.32445985 0.11778021 0.22791497
 0.32246943 0.57096255 0.34187077 0.66303712 0.4480054  0.51915126
 0.32005958 0.61113962 0.55304193 0.60169864 0.4953435  0.30461747
 0.50154573 0.28275765 0.44866543 0.22949132 0.22081998 0.