In [1]:
import numpy as np
import tqdm

In [2]:
def hardlims(input):
  return (input >0 ).astype(float)

In [3]:
def delta_rule(X,Y, weights,n_epochs):
  dims = X.shape[-1]
  for _ in tqdm.tqdm(range(n_epochs)):
    for x,y in zip(X,Y):
      sum = x@weights
      e = y - hardlims(sum)
      # print(e*x)
      weights = weights + e*x
      # print("w", weights, "k")
  return weights


#Dane separowalne

In [4]:
#AND
n_inputs = 100
n_dims = 3
X = np.random.random((n_inputs, n_dims + 1))
Y = np.random.randint(0,2,size=(n_inputs))
#na 1 wspolrzednej wartosci dodatnie lub ujemne dadza separowalnosc
X[Y== 0] = X[Y== 0] + 100
X[Y== 1] = X[Y== 1] - 100

In [5]:
X[:5]

array([[100.41407851, 100.08727672, 100.55732185, 100.14936751],
       [-99.21524867, -99.50020043, -99.67832198, -99.73490032],
       [100.60143038, 100.89375917, 100.7028496 , 100.26994501],
       [-99.00573469, -99.07183558, -99.42107341, -99.98482545],
       [-99.2064087 , -99.80487777, -99.12958417, -99.55554803]])

In [6]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.53548552 0.16903326 0.05588477 0.32281605]
[ 108.63781094 -107.71370012  108.92151464 -107.59540408 -107.67190316
  109.01267178 -107.57434261 -107.78148841  108.91851558  108.66527849
  108.56122866  108.78632689 -107.59999373  108.90568804  109.11802891
 -107.83598041  108.88419004 -107.60914264 -107.89026319  108.84316574
 -107.83865042  109.04505532  109.15832963 -107.75139916  109.06014995
 -108.08463097 -107.4627392  -107.91525637 -107.72781936 -107.94557664
  109.00325005  108.85412874  108.77452863 -107.80808267 -107.99594363
 -107.71552901 -107.55899233 -107.9260774  -107.79543095  108.72474815
  109.07472254 -107.62075685  108.94098883 -107.69138471  109.21304812
 -107.84015043 -107.6455034   108.9841063  -107.8303406  -107.63968387
 -107.94410035 -107.85075534 -107.552526   -107.54871841  108.8659316
 -108.12621318 -107.92188014  108.5625684  -107.5057183   108.74644651
 -107.89067174  108.89887763  108.86318582  108.68415726  108.54459668
  109.02429523  108.84230766 -10

In [7]:
weights = delta_rule(X,Y, weights,n_epochs=10000)

100%|██████████| 10000/10000 [00:10<00:00, 952.96it/s]


In [8]:
print("Wagi")
print(X@weights)
predictions = hardlims(X@weights)
print(predictions)
print(Y)
print(np.average(np.abs(Y - predictions)))


Wagi
[-40133.48310392  39825.37045332 -40259.44043929  39760.7383426
  39781.87729569 -40192.90919255  39765.01426269  39778.40902672
 -40309.5408712  -40197.68634912 -40145.90116495 -40181.43974664
  39735.07456175 -40196.77458527 -40246.8346545   39803.90324743
 -40171.96418076  39760.26806782  39832.69191157 -40260.26400187
  39786.72881914 -40273.13489283 -40326.04630831  39817.21260557
 -40249.28193931  39869.212807    39719.27001846  39860.63720669
  39756.42617932  39888.4996463  -40233.94715251 -40210.66972338
 -40181.35919677  39804.83166329  39842.3013256   39861.2931548
  39719.94124722  39890.94436807  39795.66516883 -40191.68386814
 -40227.31915525  39781.93481399 -40231.83330867  39810.09804066
 -40269.11583639  39836.48325687  39765.04692433 -40255.57679263
  39853.31520321  39754.3520162   39886.77647079  39776.01182362
  39773.37161718  39789.38901496 -40271.85198751  39895.48256964
  39811.19086184 -40150.01633998  39703.92650977 -40136.40053665
  39837.65921566 -4015

#Dane nieseparowalne

In [9]:
#AND
n_inputs = 100
n_dims = 2
X = np.random.random((n_inputs, n_dims + 1))
Y = np.random.randint(0,2,size=(n_inputs))

In [10]:
weights = np.random.random(size=(X.shape[-1]))
print(weights)
print(X@weights)
print(hardlims(X@weights))
print("")

[0.93355044 0.39227328 0.10113024]
[1.00314655 1.07853725 0.78476637 0.36653603 0.74012394 0.64772477
 0.9513569  0.93888982 0.47444712 0.55713607 0.50316669 0.87018444
 0.77380586 0.8697475  0.64697673 0.68589861 0.94749198 1.02146368
 0.21765218 0.98472716 1.06221278 0.90662672 0.90455974 0.58609829
 0.34427712 0.53048267 0.54448873 0.38678219 0.27412049 1.34794067
 0.59071267 1.05650218 0.53202022 0.41727188 1.20262056 1.03497073
 0.7664737  0.56462489 0.83841263 0.64470514 0.95968814 0.20109337
 0.58300572 0.96624613 0.75505669 1.05708116 1.0277073  1.2243343
 1.10357983 0.62532327 0.92579555 0.77121405 0.31957671 1.28948875
 0.62145074 0.79618862 0.75351686 0.71031488 0.79905028 0.77989966
 1.05873803 0.21603197 1.0890407  0.88925805 0.25248339 0.91950388
 0.80129321 0.38741103 0.73560778 0.49472763 0.38541235 1.19736156
 0.72366837 0.34331439 0.7075858  0.69690277 0.76705232 0.71083489
 0.44747444 0.87114676 1.05320734 1.07944703 1.04292769 0.52577496
 0.45763533 0.60744021 0.500

In [11]:
weights = delta_rule(X,Y, weights,n_epochs=10000)

100%|██████████| 10000/10000 [00:08<00:00, 1194.00it/s]


In [12]:
print("Wagi")
print(X@weights)
predictions = hardlims(X@weights)
print(predictions)
print(Y)
print(np.average(np.abs(Y - predictions)))

Wagi
[ 0.47945405  0.0588358   0.10472895  0.46900616 -0.01238199  0.66102203
  0.94649798  0.2440063   0.14005882  0.6258647   0.56707182  0.62432433
  0.29170197  0.47498421  0.53197447  0.55163443  0.32095158  0.28642577
  0.42441698  0.67629579  0.77383839  0.79954593  0.30933563  0.74419947
  0.37821272  0.6064162   0.6981794  -0.00895421  0.77198088  0.72285739
  0.11460767  0.0087036   0.47401554  0.22807746  0.79492912  0.84637263
  0.74119243  0.12951133  0.87240615  0.02505874  0.58150577  0.54418128
  0.03325444  0.57637701  0.83762474  0.4467553   0.30193808  0.65505487
  0.60777361  0.67378     0.8626518   0.63798156  0.62795429  0.59717458
  0.71727715  0.64101477  0.865012    0.28998971  0.25592987  0.20872888
  0.4541833   0.15156803  0.40047136  0.6204615   0.47116915  0.20898396
  0.20749629  0.64357702  0.58387014  0.70224626 -0.04411942  0.12966056
  0.32834074  0.343728    0.46873435  0.53028509  0.72249015  0.68712827
  0.12958361  0.8097415   0.09418097  0.416892